trigger:
  batch: true
  branches:
    include:
    - '*'

stages:
- stage: onPush
  condition: |
      and(
        ne(variables['Build.SourceBranch'], 'refs/heads/releases'),
        not(startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
      )
  jobs:
  - job: onPushJob
    pool:
      vmImage: 'ubuntu-18.04'

    steps:
    - script: env | sort
      displayName: 'Environment / Context'

    - task: UsePythonVersion@0
      displayName: 'Use Python 3.7'
      inputs:
        versionSpec: 3.7

    - checkout: self
      persistCredentials: true
      clean: true
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

    - script: |
        python -m pip install --upgrade pip nutter
        # this is because of the old dependency inside Nutter
        python -m pip install --upgrade databricks-cli
      displayName: 'Install dependencies'
     
    - script: |
        echo "Checking out the $(branchName) branch"
        databricks repos update --path $(STAGING_DIRECTORY) --branch "$(Build.SourceBranchName)"
      env:
        DATABRICKS_HOST: $(STAGING_DATABRICKS_HOST)
        DATABRICKS_TOKEN: $(STAGING_DATABRICKS_TOKEN)
      displayName: 'Update Staging project'
      
    - script: |
        nutter run "$(STAGING_DIRECTORY)/tests/" --cluster_id $(CLUSTER_ID) --recursive --junit_report --timeout 500
      env:
        DATABRICKS_HOST: $(STAGING_DATABRICKS_HOST)
        DATABRICKS_TOKEN: $(STAGING_DATABRICKS_TOKEN)
        
      displayName: 'Execute Nutter tests'
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/test-*.xml' 
        failTaskOnFailedTests: true

- stage: onRelease
  condition: |
    eq(variables['Build.SourceBranch'], 'refs/heads/releases')
  jobs:
  - job: onReleaseJob
    pool:
      vmImage: 'ubuntu-18.04'

    steps:
      - script: env | sort
        displayName: 'Environment / Context'

      - task: UsePythonVersion@0
        displayName: 'Use Python 3.7'
        inputs:
          versionSpec: 3.7

      - checkout: self
        persistCredentials: true
        clean: true
        displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

      - script: |
          python -m pip install --upgrade pip nutter
          # this is because of the old dependency inside Nutter
          python -m pip install --upgrade databricks-cli
        displayName: 'Install dependencies'
        
      - script: |
          echo "Checking out the releases branch"
          databricks repos update --path $(PROD_DIRECTORY) --branch "$(Build.SourceBranchName)"
        env:
          DATABRICKS_HOST: $(PROD_DATABRICKS_HOST)
          DATABRICKS_TOKEN: $(PROD_DATABRICKS_TOKEN)
        displayName: 'Update Prod repository'
